// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PIA.Infrastructure.Persistence;

#nullable disable

namespace PIA.Infrastructure.Migrations
{
    [DbContext(typeof(PiaDbContext))]
    [Migration("20260908090000_FaceEnrollmentReview")]
    partial class FaceEnrollmentReview
    {
        /// <inheritdoc />
        /// <remarks>
        /// Deliberately left minimal rather than a full model-snapshot copy (unlike EF's usual
        /// auto-generated Designer files) - this was hand-written without access to `dotnet ef`
        /// tooling. It does not affect applying this migration (Up()/Down() in the sibling file
        /// is what actually runs). It only matters if EF needs to diff against THIS specific
        /// migration's target model, which `dotnet ef migrations add` does not do - it diffs
        /// against PiaDbContextModelSnapshot.cs (already updated with the new column) instead. If
        /// you have `dotnet ef` available, regenerating this migration properly (delete this
        /// migration + its .cs file, re-run `dotnet ef migrations add FaceEnrollmentReview`)
        /// is still recommended when convenient.
        /// </remarks>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
