// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIA.Infrastructure.Persistence;

#nullable disable

namespace PIA.Infrastructure.Migrations
{
    [DbContext(typeof(PiaDbContext))]
    partial class PiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PIA.Domain.Entities.AttendanceChallengeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("ChallengeJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("challenge_json");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("client_ip");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateOnly>("DatePk")
                        .HasColumnType("date")
                        .HasColumnName("date_pk");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("EventType")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<double?>("IssueDistanceM")
                        .HasColumnType("double")
                        .HasColumnName("issue_distance_m");

                    b.Property<string>("IssueGeofenceState")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("issue_geofence_state");

                    b.Property<decimal?>("IssueLatitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("issue_latitude");

                    b.Property<decimal?>("IssueLongitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("issue_longitude");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("JwtJti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("jwt_jti");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("varbinary(32)")
                        .HasColumnName("nonce");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at_utc");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_agent");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_challenge_sessions");

                    b.HasIndex("Nonce")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_challenge_sessions_nonce");

                    b.HasIndex("State", "ExpiresAtUtc")
                        .HasDatabaseName("ix_attendance_challenge_sessions_state_expires_at_utc");

                    b.HasIndex("InternProfileId", "State", "ExpiresAtUtc")
                        .HasDatabaseName("ix_attendance_challenge_sessions_intern_profile_id_state_expire");

                    b.ToTable("attendance_challenge_sessions", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.AttendanceDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ArrivalAccuracyM")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("arrival_accuracy_m");

                    b.Property<DateTime?>("ArrivalAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrival_at_utc");

                    b.Property<double?>("ArrivalDistanceM")
                        .HasColumnType("double")
                        .HasColumnName("arrival_distance_m");

                    b.Property<long?>("ArrivalEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("arrival_event_id");

                    b.Property<string>("ArrivalGeofence")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("arrival_geofence");

                    b.Property<decimal?>("ArrivalLat")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("arrival_lat");

                    b.Property<decimal?>("ArrivalLng")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("arrival_lng");

                    b.Property<string>("ArrivalMode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("arrival_mode");

                    b.Property<string>("ArrivalSource")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("arrival_source");

                    b.Property<bool>("AutoClosed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("auto_closed");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal?>("DepartureAccuracyM")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("departure_accuracy_m");

                    b.Property<DateTime?>("DepartureAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departure_at_utc");

                    b.Property<double?>("DepartureDistanceM")
                        .HasColumnType("double")
                        .HasColumnName("departure_distance_m");

                    b.Property<long?>("DepartureEventId")
                        .HasColumnType("bigint")
                        .HasColumnName("departure_event_id");

                    b.Property<string>("DepartureGeofence")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("departure_geofence");

                    b.Property<decimal?>("DepartureLat")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("departure_lat");

                    b.Property<decimal?>("DepartureLng")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("departure_lng");

                    b.Property<string>("DepartureMode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("departure_mode");

                    b.Property<string>("DepartureSource")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("departure_source");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<bool>("IsEarlyLeave")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_early_leave");

                    b.Property<bool>("IsLate")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_late");

                    b.Property<bool>("MarkedBySystem")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("marked_by_system");

                    b.Property<bool>("RequiresReview")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_review");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("void_reason");

                    b.Property<DateTime?>("VoidedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("voided_at_utc");

                    b.Property<int?>("VoidedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("voided_by_user_id");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date")
                        .HasColumnName("work_date");

                    b.Property<int?>("WorkedMinutes")
                        .HasColumnType("int")
                        .HasColumnName("worked_minutes");

                    b.HasKey("Id")
                        .HasName("pk_attendance_days");

                    b.HasIndex("InternProfileId", "WorkDate")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_days_intern_profile_id_work_date");

                    b.HasIndex("WorkDate", "Status")
                        .HasDatabaseName("ix_attendance_days_work_date_status");

                    b.ToTable("attendance_days", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.AttendanceEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AccuracyM")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("accuracy_m");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("app_version");

                    b.Property<long?>("AttendanceDayId")
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_day_id");

                    b.Property<Guid?>("ChallengeSessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("challenge_session_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("device_model");

                    b.Property<double>("DistanceFromDepartmentM")
                        .HasColumnType("double")
                        .HasColumnName("distance_from_department_m");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("event_type");

                    b.Property<long?>("FaceVerificationResultId")
                        .HasColumnType("bigint")
                        .HasColumnName("face_verification_result_id");

                    b.Property<string>("GeofenceState")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("geofence_state");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("SelfieFileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("selfie_file_id");

                    b.HasKey("Id")
                        .HasName("pk_attendance_events");

                    b.HasIndex("InternProfileId", "OccurredAtUtc")
                        .HasDatabaseName("ix_attendance_events_intern_profile_id_occurred_at_utc");

                    b.ToTable("attendance_events", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.AttendanceMedia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AttemptId")
                        .HasColumnType("bigint")
                        .HasColumnName("attempt_id");

                    b.Property<int>("Bytes")
                        .HasColumnType("int")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("Encrypted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("encrypted");

                    b.Property<short?>("Height")
                        .HasColumnType("smallint")
                        .HasColumnName("height");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_primary");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("kind");

                    b.Property<ulong>("Phash")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("phash");

                    b.Property<DateTime?>("PurgedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("purged_at_utc");

                    b.Property<DateTime>("RetentionExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retention_expires_at_utc");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("sha256");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("slot");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("storage_key");

                    b.Property<short?>("Width")
                        .HasColumnType("smallint")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_attendance_media");

                    b.HasIndex("Phash")
                        .HasDatabaseName("ix_attendance_media_phash");

                    b.HasIndex("RetentionExpiresAtUtc", "PurgedAtUtc")
                        .HasDatabaseName("ix_attendance_media_retention_expires_at_utc_purged_at_utc");

                    b.ToTable("attendance_media", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.AttendanceOverride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AdminCountersignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("admin_countersigned_by_user_id");

                    b.Property<long?>("AttendanceDayId")
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_day_id");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("client_ip");

                    b.Property<DateOnly>("DatePk")
                        .HasColumnType("date")
                        .HasColumnName("date_pk");

                    b.Property<DateTime?>("DecidedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("decided_at_utc");

                    b.Property<string>("DecidedByRole")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("decided_by_role");

                    b.Property<int?>("DecidedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("Decision")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("decision");

                    b.Property<double?>("DistanceM")
                        .HasColumnType("double")
                        .HasColumnName("distance_m");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("event_type");

                    b.Property<string>("GeofenceStateAtRequest")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("geofence_state_at_request");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("justification");

                    b.Property<DateTime>("MarkedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("marked_at_utc");

                    b.Property<bool>("QuotaExceeded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("quota_exceeded");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("reason_code");

                    b.Property<string>("RequestNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("request_note");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at_utc");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("requested_by_user_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_attendance_overrides");

                    b.HasIndex("InternProfileId", "DatePk")
                        .HasDatabaseName("ix_attendance_overrides_intern_profile_id_date_pk");

                    b.ToTable("attendance_overrides", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.AttendanceVerificationAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int")
                        .HasColumnName("attempt_number");

                    b.Property<long?>("AttendanceDayId")
                        .HasColumnType("bigint")
                        .HasColumnName("attendance_day_id");

                    b.Property<string>("AttestationVerdict")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("attestation_verdict");

                    b.Property<decimal?>("BlurVariance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("blur_variance");

                    b.Property<string>("ClientReasonCode")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("client_reason_code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("DatePk")
                        .HasColumnType("date")
                        .HasColumnName("date_pk");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("device_id");

                    b.Property<double?>("DistanceM")
                        .HasColumnType("double")
                        .HasColumnName("distance_m");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("event_type");

                    b.Property<decimal?>("FaceMatchBestOther")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("face_match_best_other");

                    b.Property<decimal?>("FaceMatchScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("face_match_score");

                    b.Property<long?>("FaceTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("face_template_id");

                    b.Property<string>("FlagsJson")
                        .HasColumnType("json")
                        .HasColumnName("flags_json");

                    b.Property<int?>("FrameCount")
                        .HasColumnType("int")
                        .HasColumnName("frame_count");

                    b.Property<string>("GeofenceState")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("geofence_state");

                    b.Property<decimal?>("GpsAccuracyM")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("gps_accuracy_m");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<string>("InternalReasonCode")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("internal_reason_code");

                    b.Property<bool?>("LocationMocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("location_mocked");

                    b.Property<decimal?>("PadLiveProbBest")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pad_live_prob_best");

                    b.Property<decimal?>("PadLiveProbMean")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pad_live_prob_mean");

                    b.Property<int?>("PayloadBytes")
                        .HasColumnType("int")
                        .HasColumnName("payload_bytes");

                    b.Property<decimal?>("QualityScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("quality_score");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int")
                        .HasColumnName("risk_score");

                    b.Property<int?>("ServerLatencyMs")
                        .HasColumnType("int")
                        .HasColumnName("server_latency_ms");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("session_id");

                    b.Property<string>("TraceJson")
                        .HasColumnType("json")
                        .HasColumnName("trace_json");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_attendance_verification_attempts");

                    b.HasIndex("InternProfileId", "DatePk")
                        .HasDatabaseName("ix_attendance_verification_attempts_intern_profile_id_date_pk");

                    b.HasIndex("Verdict", "RiskScore", "CreatedAtUtc")
                        .HasDatabaseName("ix_attendance_verification_attempts_verdict_risk_score_created_");

                    b.ToTable("attendance_verification_attempts", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("action");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("actor_role");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterJson")
                        .HasColumnType("json")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("json")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId", "CreatedAtUtc")
                        .HasDatabaseName("ix_audit_logs_actor_user_id_created_at_utc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at_utc");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("certificate_number");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("GeneratedFileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("generated_file_id");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at_utc");

                    b.Property<int?>("IssuedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("issued_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RenderedBy")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("rendered_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("Id")
                        .HasName("pk_certificates");

                    b.HasIndex("CertificateNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_certificates_certificate_number");

                    b.HasIndex("InternProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_certificates_intern_profile_id");

                    b.ToTable("certificates", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.CertificateTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("MergeFieldsJson")
                        .HasColumnType("json")
                        .HasColumnName("merge_fields_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_certificate_templates");

                    b.ToTable("certificate_templates", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<int>("GeofenceRadiusMeters")
                        .HasColumnType("int")
                        .HasColumnName("geofence_radius_meters");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_departments_name");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.DepartmentCodeSequence", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.Property<int>("NextValue")
                        .HasColumnType("int")
                        .HasColumnName("next_value");

                    b.HasKey("DepartmentId", "Year")
                        .HasName("pk_department_code_sequences");

                    b.ToTable("department_code_sequences", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.DeviceBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BoundAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("bound_at_utc");

                    b.Property<int?>("BoundByUserId")
                        .HasColumnType("int")
                        .HasColumnName("bound_by_user_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<string>("LastAttestationVerdict")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("last_attestation_verdict");

                    b.Property<DateTime?>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("os_version");

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_device_bindings");

                    b.HasIndex("InternProfileId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_bindings_intern_profile_id_device_id");

                    b.ToTable("device_bindings", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentFileIdsJson")
                        .HasColumnType("json")
                        .HasColumnName("attachment_file_ids_json");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("mediumtext")
                        .HasColumnName("html_body");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("subject");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("template_key");

                    b.Property<string>("TextBody")
                        .HasColumnType("mediumtext")
                        .HasColumnName("text_body");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("to_address");

                    b.Property<string>("ToName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("to_name");

                    b.HasKey("Id")
                        .HasName("pk_email_outbox_messages");

                    b.HasIndex("Status", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_email_outbox_messages_status_next_attempt_at_utc");

                    b.ToTable("email_outbox_messages", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.FaceTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("CrossMatchScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cross_match_score");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("varbinary(2048)")
                        .HasColumnName("embedding");

                    b.Property<short?>("EmbeddingDim")
                        .HasColumnType("smallint")
                        .HasColumnName("embedding_dim");

                    b.Property<decimal?>("EmbeddingNorm")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("embedding_norm");

                    b.Property<string>("EnrollmentReason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("enrollment_reason");

                    b.Property<string>("ExternalCollection")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("external_collection");

                    b.Property<string>("ExternalFaceId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("external_face_id");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<decimal?>("IntraSetMinScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("intra_set_min_score");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("model_id");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("provider");

                    b.Property<decimal?>("QualityScore")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("quality_score");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("revoked_reason");

                    b.Property<Guid>("SourceSessionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("source_session_id");

                    b.Property<DateTime?>("SupersededAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("superseded_at_utc");

                    b.Property<long?>("SupersededByTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("superseded_by_template_id");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_face_templates");

                    b.HasIndex("InternProfileId", "IsActive")
                        .HasDatabaseName("ix_face_templates_intern_profile_id_is_active");

                    b.HasIndex("InternProfileId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_face_templates_intern_profile_id_version");

                    b.ToTable("face_templates", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.FaceVerificationResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ActiveChallengePassed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active_challenge_passed");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("failure_reason");

                    b.Property<int>("FramesEvaluated")
                        .HasColumnType("int")
                        .HasColumnName("frames_evaluated");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("int")
                        .HasColumnName("latency_ms");

                    b.Property<decimal?>("LiveScore")
                        .HasColumnType("decimal(6,5)")
                        .HasColumnName("live_score");

                    b.Property<bool>("MatchPassed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("match_passed");

                    b.Property<decimal?>("MatchSimilarity")
                        .HasColumnType("decimal(6,5)")
                        .HasColumnName("match_similarity");

                    b.Property<decimal?>("MatchThreshold")
                        .HasColumnType("decimal(6,5)")
                        .HasColumnName("match_threshold");

                    b.Property<bool>("OverallPassed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("overall_passed");

                    b.Property<bool>("PassivePassed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("passive_passed");

                    b.Property<decimal?>("PrintAttackScore")
                        .HasColumnType("decimal(6,5)")
                        .HasColumnName("print_attack_score");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider_name");

                    b.Property<string>("RawPayloadJson")
                        .HasColumnType("json")
                        .HasColumnName("raw_payload_json");

                    b.Property<decimal?>("ReplayAttackScore")
                        .HasColumnType("decimal(6,5)")
                        .HasColumnName("replay_attack_score");

                    b.HasKey("Id")
                        .HasName("pk_face_verification_results");

                    b.ToTable("face_verification_results", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.GithubSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("repository_url");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_github_submissions");

                    b.HasIndex("InternProfileId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_github_submissions_intern_profile_id_version");

                    b.ToTable("github_submissions", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_holidays");

                    b.HasIndex("Date", "DepartmentId")
                        .HasDatabaseName("ix_holidays_date_department_id");

                    b.ToTable("holidays", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.IdCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at_utc");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("blood_group");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("card_number");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<Guid?>("GeneratedFileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("generated_file_id");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<DateTime?>("IssuedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("issued_at_utc");

                    b.Property<int?>("IssuedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("issued_by_user_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at_utc");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_id_cards");

                    b.HasIndex("CardNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_id_cards_card_number");

                    b.HasIndex("InternProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_id_cards_intern_profile_id");

                    b.ToTable("id_cards", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.InternDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("document_type");

                    b.Property<Guid>("FileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("file_id");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_intern_documents");

                    b.HasIndex("InternProfileId", "DocumentType", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_intern_documents_intern_profile_id_document_type_version");

                    b.ToTable("intern_documents", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.InternProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<Guid?>("ApprovedPhotoFileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("approved_photo_file_id");

                    b.Property<string>("AttendanceAccommodation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("attendance_accommodation");

                    b.Property<DateOnly?>("AttendanceAccommodationExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("attendance_accommodation_expires_on");

                    b.Property<string>("AttendanceAccommodationReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("attendance_accommodation_reason");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("blood_group");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<TimeOnly>("DailyEndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("daily_end_time");

                    b.Property<TimeOnly>("DailyStartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("daily_start_time");

                    b.Property<string>("DegreeProgram")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("degree_program");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("FaceEnrollmentStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("face_enrollment_status");

                    b.Property<string>("GithubRepoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("github_repo_url");

                    b.Property<string>("GithubStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("github_status");

                    b.Property<string>("InternCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("intern_code");

                    b.Property<DateOnly>("InternshipEndDate")
                        .HasColumnType("date")
                        .HasColumnName("internship_end_date");

                    b.Property<DateOnly>("InternshipStartDate")
                        .HasColumnType("date")
                        .HasColumnName("internship_start_date");

                    b.Property<int>("MentorId")
                        .HasColumnType("int")
                        .HasColumnName("mentor_id");

                    b.Property<bool>("ProfileLocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("profile_locked");

                    b.Property<DateTime?>("ProfilePhotoApprovedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("profile_photo_approved_at_utc");

                    b.Property<int?>("ProfilePhotoApprovedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("profile_photo_approved_by_user_id");

                    b.Property<string>("ProfilePhotoStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("profile_photo_status");

                    b.Property<bool>("SelfDetailsSubmitted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("self_details_submitted");

                    b.Property<DateTime?>("SelfDetailsSubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("self_details_submitted_at_utc");

                    b.Property<string>("UniversityName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("university_name");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("VerificationRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("verification_remarks");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("verification_status");

                    b.Property<DateTime?>("VerifiedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("verified_at_utc");

                    b.Property<int?>("VerifiedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("verified_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_intern_profiles");

                    b.HasIndex("InternCode")
                        .IsUnique()
                        .HasDatabaseName("ix_intern_profiles_intern_code");

                    b.HasIndex("MentorId")
                        .HasDatabaseName("ix_intern_profiles_mentor_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_intern_profiles_user_id");

                    b.ToTable("intern_profiles", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.JobRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at_utc");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("int")
                        .HasColumnName("items_processed");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at_utc");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("succeeded");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id")
                        .HasName("pk_job_runs");

                    b.HasIndex("JobName", "StartedAtUtc")
                        .HasDatabaseName("ix_job_runs_job_name_started_at_utc");

                    b.ToTable("job_runs", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionRoute")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("action_route");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at_utc");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("RelatedEntityId")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAtUtc")
                        .HasDatabaseName("ix_notifications_recipient_user_id_is_read_created_at_utc");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.ProjectAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at_utc");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("file_id");

                    b.Property<int>("InternProfileId")
                        .HasColumnType("int")
                        .HasColumnName("intern_profile_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_project_assignments");

                    b.HasIndex("InternProfileId")
                        .HasDatabaseName("ix_project_assignments_intern_profile_id");

                    b.ToTable("project_assignments", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("created_by_ip");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("char(36)")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_file_name");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("storage_key");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_stored_files");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_stored_files_owner_user_id");

                    b.ToTable("stored_files", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnic")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("cnic");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeactivatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_count");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end_utc");

                    b.Property<bool>("MustResetPassword")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("must_reset_password");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("password_changed_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Cnic")
                        .IsUnique()
                        .HasDatabaseName("ix_users_cnic")
                        .HasFilter("`cnic` IS NOT NULL");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_users_department_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Role", "DepartmentId")
                        .HasDatabaseName("ix_users_role_department_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PIA.Domain.Entities.AttendanceDay", b =>
                {
                    b.HasOne("PIA.Domain.Entities.InternProfile", "InternProfile")
                        .WithMany("AttendanceDays")
                        .HasForeignKey("InternProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_days_intern_profiles_intern_profile_id");

                    b.Navigation("InternProfile");
                });

            modelBuilder.Entity("PIA.Domain.Entities.Certificate", b =>
                {
                    b.HasOne("PIA.Domain.Entities.InternProfile", "InternProfile")
                        .WithOne("Certificate")
                        .HasForeignKey("PIA.Domain.Entities.Certificate", "InternProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_certificates_intern_profiles_intern_profile_id");

                    b.Navigation("InternProfile");
                });

            modelBuilder.Entity("PIA.Domain.Entities.DepartmentCodeSequence", b =>
                {
                    b.HasOne("PIA.Domain.Entities.Department", "Department")
                        .WithMany("CodeSequences")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_code_sequences_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PIA.Domain.Entities.FaceTemplate", b =>
                {
                    b.HasOne("PIA.Domain.Entities.InternProfile", "InternProfile")
                        .WithMany("FaceTemplates")
                        .HasForeignKey("InternProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_face_templates_intern_profiles_intern_profile_id");

                    b.Navigation("InternProfile");
                });

            modelBuilder.Entity("PIA.Domain.Entities.GithubSubmission", b =>
                {
                    b.HasOne("PIA.Domain.Entities.InternProfile", "InternProfile")
                        .WithMany("GithubSubmissions")
                        .HasForeignKey("InternProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_github_submissions_intern_profiles_intern_profile_id");

                    b.Navigation("InternProfile");
                });

            modelBuilder.Entity("PIA.Domain.Entities.IdCard", b =>
                {
                    b.HasOne("PIA.Domain.Entities.InternProfile", "InternProfile")
                        .WithOne("IdCard")
                        .HasForeignKey("PIA.Domain.Entities.IdCard", "InternProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_id_cards_intern_profiles_intern_profile_id");

                    b.Navigation("InternProfile");
                });

            modelBuilder.Entity("PIA.Domain.Entities.InternDocument", b =>
                {
                    b.HasOne("PIA.Domain.Entities.InternProfile", "InternProfile")
                        .WithMany("Documents")
                        .HasForeignKey("InternProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intern_documents_intern_profiles_intern_profile_id");

                    b.Navigation("InternProfile");
                });

            modelBuilder.Entity("PIA.Domain.Entities.InternProfile", b =>
                {
                    b.HasOne("PIA.Domain.Entities.User", "Mentor")
                        .WithMany("MenteeProfiles")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_intern_profiles_users_mentor_id");

                    b.HasOne("PIA.Domain.Entities.User", "User")
                        .WithOne("InternProfile")
                        .HasForeignKey("PIA.Domain.Entities.InternProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_intern_profiles_users_user_id");

                    b.Navigation("Mentor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIA.Domain.Entities.Notification", b =>
                {
                    b.HasOne("PIA.Domain.Entities.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_recipient_user_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("PIA.Domain.Entities.ProjectAssignment", b =>
                {
                    b.HasOne("PIA.Domain.Entities.InternProfile", "InternProfile")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("InternProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_assignments_intern_profiles_intern_profile_id");

                    b.Navigation("InternProfile");
                });

            modelBuilder.Entity("PIA.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("PIA.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PIA.Domain.Entities.User", b =>
                {
                    b.HasOne("PIA.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PIA.Domain.Entities.Department", b =>
                {
                    b.Navigation("CodeSequences");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PIA.Domain.Entities.InternProfile", b =>
                {
                    b.Navigation("AttendanceDays");

                    b.Navigation("Certificate");

                    b.Navigation("Documents");

                    b.Navigation("FaceTemplates");

                    b.Navigation("GithubSubmissions");

                    b.Navigation("IdCard");

                    b.Navigation("ProjectAssignments");
                });

            modelBuilder.Entity("PIA.Domain.Entities.User", b =>
                {
                    b.Navigation("InternProfile");

                    b.Navigation("MenteeProfiles");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
